### ISSUE TITLE
Last (or single) XDR data block is ignored if no checksum

### ISSUE THREAD

**Issue by ch-fb** [TwoCanPlugIn/EngineDashboard#5]
I see that sentences without checksums are accepted (which is fine), but in such a case the last (or the single) transducer data block is not read. E.g.:

$IIXDR,E,99.00,P,FUEL#0
      (is not accepted)

$IIXDR,E,99.00,P,FUEL#0,E,99.00,P,FRESHWATER#0
      (Freshwater is not accepted)

$IIXDR,E,99.00,P,FUEL#0,E,99.00,P,FRESHWATER#0,
      (with the coma it is accepted)

I guess there is a tiny bug in the parser...
cheers,
Christian

**Comment by TwoCanPlugIn** [comment]
I've never tested using sentences without checksums. The NMEA 183 libraries that I use (and in fact are the same libraries that OpenCPN uses), should check for valid checksums. Without debugging the libraries, I do not understand why the plugin even attempts to parse sentences without checksums. 

Even though OpenCPN has an option "Ignore checksum" which I assume allows OpenCPN to ignore the "preparse" method of the libraries. I do not know if a plugin can determine whether OpenCPN has enabled this option. 

Nonetheless, I think it is "safer" to require checksums and I think that most modern sensors & multiplexers generate NMEA 183 sentences with checksums.

It is worrying however that the library doesn't seem to correctly validate the sentences. Worth investigating.

**Comment by ch-fb** [comment]
thanks for your quick response. yes, I had to uncheck OpenCPN's option  to run these tests. It almost seems the parser sees
"value," or "value*" as a field rather than ",value". The parsing is done in the plugin, or?

**Comment by TwoCanPlugIn** [comment]
Parsing is done in the NMEA 183 classes. They have historically been used by OpenCPN, but in general OpenCPN only uses the navigation oriented classes (GGA, GGL, RMC, RMB), Autopilot classes (APB, XTE, RMC.) and the AIS Classes (VDO, VDM). I think it would only be other plugins (Dashboard Tactics come to mind) that use other NMEA 183 sentences such as XDR.
When you mean 'tests', I presume you are generating your own XDR sentences rather than using the output from modern multiplexers/gateways which would append checksums. If you had to explicitly turn off NMEA183 checksums, which is not something most users would do, other than at some stage investigating the behavior of the parser, I'm going to close this.
